Add namespace to O_RDWR, O_CREAT, O_AT_END
earlephilhower/ESP8266SdFat pull request #5
Opened 2020-04-19 20:57 UTC by danielbuechele

When compiling the project, I am getting an error stating these three variables are not defined.
```
/Users/danielbuechele/Library/Arduino15/packages/esp8266/hardware/esp8266/2.6.3/libraries/ESP8266SdFat/src/FatLib/ArduinoFiles.h:42:21: error: 'O_RDWR' was not declared in this scope
 #define FILE_WRITE (O_RDWR | O_CREAT | O_AT_END)
```
Adding the namespace to these variables fixes the problem for me. Can we add the namespace like this?

2020-04-19 21:13 UTC, earlephilhower requested changes
The `ArduinoFiles.h` and things which use it do not work on the ESP8266.  I believe this is part of the code that implements the SDFat `File` type which is incompatible with the 8266's implementation and should not be used.

What exactly are you trying to compile/run?  Do you have a MCVE for the error?

2020-04-19 21:41 UTC, danielbuechele commented
I am running an [embedXcode](https://embedxcode.weebly.com) project. Would such a project be helpful for you as well?
But as you are saying `ArduinoFiles.h` should not be used at all on ESP8266? Then it looks like in my project `ENABLE_ARDUINO_FEATURES` is defined and shouldn't be?

2020-04-19 22:11 UTC, earlephilhower commented
I think your summation is correct.  ESP8266SdFat supports the Arduino `File` classes and methods in the Arduino code.

Now, if you need it you could go to Grieman's upstream repo and use that directly w/o any of my changes.  It should work, but not be compatible if you write your own code expecting `File` to work.

2021-11-05 23:50 UTC, earlephilhower commented
This is no longed valid because we've removed the namespacing thanks to upstr4eam changes.

2021-11-05 23:50 UTC, closed without merging